packages:
  - server
  - app/**
  - packages/**
  - services/**

catalog:
  axios: ^1.11.0
  sass: ^1.90.0
  element-plus: ^2.11.1
  '@vueuse/core': ^13.7.0
  mockjs: ^1.1.0
  '@types/mockjs': ^1.0.10
  vite-plugin-mock: ^3.0.2
